### ISSUE TITLE
Testing of Harbor Protocol

### ISSUE THREAD

**Issue by mahaider123** [comdex-official/networks#149]
Dear Sir,
On testing of harbor protocol, in earning tab, when i deposit CMST, the deposit tab is not working .  Please check & update the platform.
![Capture](https://user-images.githubusercontent.com/33589993/187061765-151f29cd-a5f8-4247-b802-5ad2b5e7fe2b.JPG)

**Comment by dheerajkd30** [comment]
/it was disabled for some time. Its working now.
